---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: terraform-controller
  namespace: flux-system
spec:
  interval: 1h
  url: https://flux-iac.github.io/tofu-controller
  type: default
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: terraform-controller
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tf-controller
      version: ">=0.15.0"
      sourceRef:
        kind: HelmRepository
        name: terraform-controller
        namespace: flux-system
  values:
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
      serviceAccount:
        create: true
